### ISSUE TITLE
Browser get stuck on large files (1hr video and its JSON)

### ISSUE THREAD

**Issue by ajaysh2193** [ZackAkil/video-intelligence-api-visualiser#9]
Hi Zack,

First of all, thanks for your awesome work. UI works great on smaller duration videos (~10min) and JSON to visualize the output in UI. But I faced issues on large duration videos as mentioned below:

I generated couple of JSON from Video Intelligence API on two videos of 30 mins and 60 mins duration. Once I upload video and Json in UI, browser gets freeze and stuck to load and visualize JSON output in browser. For your reference, I have 64GB RAM and 8 core of CPU in my laptop. Kindly help me to resolve this issue and any other suggestions/alternative approach to fix it.
Thanks :)

**Comment by shubham-ai** [comment]
same thing happening with me, if the video duration and large which leads to bigger json, browser get stuck and take huge amount of time to load the content or sometimes browser even crashes

**Comment by ZackAkil** [comment]
Hi @ajaysh2193, glad you find the app useful. For larger videos that is a know limitation of the app at the moment were the only workaround is to chuck up the videos before processing them 😬  or enabling fewer features when you run the Video Intelligence API e.i OCR, Person detection and Object Detection can be especially JSON rich. I'll add it as a feature request though as maybe there could be something done in javascript to help like stream reading the file 🤔
